name: pull-request

on: [pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v1
       with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
           ${{ runner.os }}-maven-

    - uses: actions/checkout@v1
      
    - name: Check Copyright	
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-args: "license:check"

    - name: Build and Test	
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-args: "clean install"

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
